version: '3'
services:
  app:
    build:
      context: ./
    tty: true
    stdin_open: true
    command: yarn start
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
